# Generated by Django 5.1 on 2024-08-21 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_auto_20240809_1616"),
    ]

    operations = [
        migrations.CreateModel(
            name="aeye_wlh_models",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("whoami", models.CharField(max_length=40)),
                ("message", models.CharField(max_length=40)),
            ],
        ),
    ]
