# Generated by Django 4.0 on 2024-08-21 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_aeye_wlh_models'),
    ]

    operations = [
        migrations.DeleteModel(
            name='aeye_wlh_models',
        ),
    ]
