#############################################################
# AEYE Web Docker Compose File
# Created By Yoonchul Chung
# Created At 2024.08.17
# Welcome to Visit Github : https://github.com/Yoonchulchung
#############################################################
version: '3.3'

services:
  nginx:
    image: nginx:alpine
    container_name: aeye_web_nginx
    ports:
      - "80:80"
    volumes:
      - ../nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
    tty: true
    stdin_open: true
    networks:
      - aeye_web

  backend:
    build:
      context: ..
      dockerfile: Docker/AEYE_Router/Dockerfile
    image: aeye_web_back:1.0
    container_name: aeye_web_back
    ports:
      - "2000:2000"
    volumes:
      - ../AEYE_Router/:/app/
    command: sh -c "python3.8 manage.py makemigrations &&
             python3.8 manage.py migrate &&
             python3.8 manage.py runserver 0.0.0.0:2000"
    tty: true
    stdin_open: true
    networks:
      - aeye_web
    depends_on:
      - db
    environment:
      - DB_NAME=mydatabase
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_HOST=db
      - DB_PORT=3306
    
  frontend:
    build:
      context: ..
      dockerfile: Docker/AEYE_Front/Dockerfile
    image: aeye_web_front:1.0
    container_name:  aeye_web_front
    ports:
      - "3000:3000"
    volumes:
      - ../AEYE_Front/AEYE_Front/:/app/
    command: sh -c "npm run build && npm start"
    tty: true
    stdin_open: true
    networks:
      - aeye_web
  
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - ../AEYE_SQL/:/var/lib/mysql
    networks:
      - aeye_web

networks:
  aeye_web:
    driver: bridge

volumes:
  db_data: