# Generated by Django 4.0 on 2024-08-21 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hal', '0003_aeye_database_read_models_aeye_database_write_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='aeye_Checkup_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('symptom', models.TextField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='aeye_database_list_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('profileImage', models.URLField(max_length=255)),
                ('numberOfVisits', models.IntegerField()),
                ('recentVisitDate', models.DateField()),
                ('severityPercentage', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='aeye_UltrasoundImage_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageUrl', models.URLField(max_length=255)),
                ('checkup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ultrasoundImages', to='hal.aeye_checkup_models')),
            ],
        ),
        migrations.CreateModel(
            name='aeye_Report_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_diagnosis', models.CharField(max_length=255)),
                ('ai_probability', models.CharField(max_length=10)),
                ('doctor_diagnosis', models.TextField()),
                ('checkup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='hal.aeye_checkup_models')),
            ],
        ),
        migrations.AddField(
            model_name='aeye_checkup_models',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkups', to='hal.aeye_database_list_models'),
        ),
    ]
