# Generated by Django 4.0 on 2024-08-21 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hal', '0004_aeye_checkup_models_aeye_database_list_models_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='aeye_database_checkup_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('symptom', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('ultrasound_images', models.JSONField()),
                ('ai_diagnosis', models.CharField(max_length=255)),
                ('ai_probability', models.CharField(max_length=10)),
                ('doctor_diagnosis', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='aeye_report_models',
            name='checkup',
        ),
        migrations.RemoveField(
            model_name='aeye_ultrasoundimage_models',
            name='checkup',
        ),
        migrations.RenameModel(
            old_name='aeye_database_list_models',
            new_name='aeye_database_patient_models',
        ),
        migrations.DeleteModel(
            name='aeye_Checkup_models',
        ),
        migrations.DeleteModel(
            name='aeye_Report_models',
        ),
        migrations.DeleteModel(
            name='aeye_UltrasoundImage_models',
        ),
        migrations.AddField(
            model_name='aeye_database_checkup_models',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkups', to='hal.aeye_database_patient_models'),
        ),
    ]
