# Generated by Django 4.0 on 2024-08-22 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hal', '0005_aeye_database_checkup_models_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aeye_database_checkup_models',
            old_name='patient',
            new_name='patientId',
        ),
        migrations.RenameField(
            model_name='aeye_database_checkup_models',
            old_name='ultrasound_images',
            new_name='ultrasound_image',
        ),
    ]
