# Generated by Django 4.0 on 2024-08-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hal', '0006_rename_patient_aeye_database_checkup_models_patientid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeye_database_checkup_models',
            name='doctor_diagnosis',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='aeye_database_checkup_models',
            name='symptom',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='aeye_database_checkup_models',
            name='ultrasound_image',
            field=models.CharField(max_length=20),
        ),
    ]
