# Generated by Django 4.0 on 2024-08-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hal', '0007_alter_aeye_database_checkup_models_doctor_diagnosis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='aeye_database_read_detail_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whoami', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='aeye_database_read_list_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whoami', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='aeye_database_read_models',
        ),
        migrations.DeleteModel(
            name='aeye_database_write_models',
        ),
    ]
